#!/usr/bin/env Rscript
source(file.path(dirname(normalizePath(sub("^--file=", "", commandArgs(FALSE)[grep("^--file=", commandArgs(FALSE))]))), "dv_shared.R"))
dv_require(c("limma","statmod","digest"))
stage <- "D02_discovery_primary"; outdir <- dv_stage_dir(stage)
d01 <- dv_stage_dir("D01_discovery_eligibility")
expr_file <- file.path(d01,"D01_discovery_eligible_expression.csv.gz")
prot_file <- file.path(d01,"D01_discovery_eligible_proteins.csv")
meta <- dv_assignment("Discovery"); expr <- dv_read_expression(expr_file, meta$UniqueSampleID, raw=TRUE)
prot <- dv_read_csv(prot_file,"PG.ProteinGroups"); if(!identical(rownames(expr),prot$PG.ProteinGroups)) dv_stop("D01 protein order mismatch")
design <- dv_design(meta); if(attr(design,"rank")!=ncol(design)) dv_stop("Primary design not full rank")
res <- dv_add_annotation(dv_fit(expr,design,dv_primary_contrast(design)))
diag <- data.frame(Metric=c("participants","proteins","design_rank","design_columns","remaining_missing_cells","normalization","transformation","imputation"), Value=c(ncol(expr),nrow(expr),qr(design)$rank,ncol(design),sum(is.na(expr)),"NONE","log2(PG.Quantity)","NONE"))
paths <- file.path(outdir,c("D02_Long_vs_Short_all_tested.csv","D02_design_matrix.csv","D02_diagnostics.csv","D02_manifest.csv")); dv_no_overwrite(paths)
dv_write(res,paths[1]); dv_write(cbind(UniqueSampleID=meta$UniqueSampleID,design),paths[2]); dv_write(diag,paths[3]); dv_write(dv_manifest(stage,c(expr_file,prot_file,DV_ASSIGNMENT),paths[1:3],list(model="abundance ~ dose + environment",ebayes="trend=TRUE; robust=TRUE",candidate_lock="NOT_PERFORMED")),paths[4])
