#!/usr/bin/env Rscript
source(file.path(dirname(normalizePath(sub("^--file=", "", commandArgs(FALSE)[grep("^--file=", commandArgs(FALSE))]))), "dv_shared.R"))
dv_require("digest");hash<-dv_assert_candidate_hash();stage<-"D09_missingness_detection_peptides";outdir<-dv_stage_dir(stage)
# Validation outcomes are optional and may only be read after a completed, unlocked D08.
metaD<-dv_assignment("Discovery");dfile<-file.path(dv_stage_dir("D01_discovery_eligibility"),"D01_discovery_eligible_expression.csv.gz");dexpr<-dv_read_expression(dfile,metaD$UniqueSampleID,FALSE)
lockf<-file.path(dv_stage_dir("D03_candidate_lock"),"D03_locked_candidates.csv");lock<-dv_read_csv(lockf,"PG.ProteinGroups");dexpr<-dexpr[match(lock$PG.ProteinGroups,rownames(dexpr)),,drop=FALSE]
summarize_layer<-function(expr,meta,split){do.call(rbind,lapply(c("Dose","Environment","Site"),function(level){grp<-switch(level,Dose=meta$TREAT1_clean,Environment=meta$Environment,Site=meta$group);do.call(rbind,lapply(unique(grp),function(g){ix<-grp==g;det<-is.finite(expr[,ix,drop=FALSE])&expr[,ix,drop=FALSE]>0;data.frame(PG.ProteinGroups=rownames(expr),Split=split,Stratifier=level,Level=g,N_total=sum(ix),N_detected=rowSums(det),Detection_rate=rowMeans(det),Missing_rate=1-rowMeans(det))}))}))}
evidence<-summarize_layer(dexpr,metaD,"Discovery");inputs<-c(dfile,lockf)
vfile<-file.path(dv_stage_dir("D08_validation"),"D08_validation_locked_raw_expression.csv.gz")
if(file.exists(vfile)){dv_assert_unlock();metaV<-dv_assignment("Validation");vexpr<-dv_read_expression(vfile,metaV$UniqueSampleID,FALSE);if(!identical(rownames(vexpr),lock$PG.ProteinGroups))dv_stop("Validation evidence universe expanded");evidence<-rbind(evidence,summarize_layer(vexpr,metaV,"Validation"));inputs<-c(inputs,vfile)}
grad<-do.call(rbind,lapply(c(.5,.6,.7,.8),function(t)data.frame(evidence[evidence$Stratifier=="Dose",c("PG.ProteinGroups","Split","Level")],Threshold=t,Reaches_threshold=evidence$Detection_rate[evidence$Stratifier=="Dose"]>=t)))
# No group-specificity rule is inferred from single-group threshold attainment.
pep_source<-file.path(DV_ROOT,"descriptive","unique_peptide_support.csv");if(file.exists(pep_source)){pep<-dv_read_csv(pep_source,"PG.ProteinGroups");pep<-pep[match(lock$PG.ProteinGroups,pep$PG.ProteinGroups),,drop=FALSE];inputs<-c(inputs,pep_source)}else{pep<-data.frame(PG.ProteinGroups=lock$PG.ProteinGroups,Unique_peptide_count=NA_integer_,Single_unique_peptide=NA,Peptide_support_status="SOURCE_NOT_AVAILABLE")}
paths<-file.path(outdir,c("D09_missingness_detection_by_stratum.csv","D09_detection_gradients.csv","D09_unique_peptide_support.csv","D09_manifest.csv"));dv_no_overwrite(paths);dv_write(evidence,paths[1]);dv_write(grad,paths[2]);dv_write(pep,paths[3]);dv_write(dv_manifest(stage,inputs,paths[1:3],list(candidate_hash=hash,detection="finite abundance AND abundance > 0",imputation="NONE",peptide_source=if(file.exists(pep_source))pep_source else "SOURCE_NOT_AVAILABLE")),paths[4])
