#!/usr/bin/env Rscript
source(file.path(dirname(normalizePath(sub("^--file=", "", commandArgs(FALSE)[grep("^--file=", commandArgs(FALSE))]))), "dv_shared.R"))
dv_require("digest");hash<-dv_assert_candidate_hash();stage<-"D10_integrated_biology";outdir<-dv_stage_dir(stage)
files<-c(D03=file.path(dv_stage_dir("D03_candidate_lock"),"D03_locked_candidates.csv"),D04=file.path(dv_stage_dir("D04_dose_trajectory"),"D04_trajectory_classification.csv"),D05=file.path(dv_stage_dir("D05_environment_specific"),"D05_candidate_environment_results.csv"),D06=file.path(dv_stage_dir("D06_environment_interaction"),"D06_candidate_interaction_results.csv"),D07=file.path(dv_stage_dir("D07_site_robustness"),"D07_leave_one_major_site_out.csv"),D08=file.path(dv_stage_dir("D08_validation"),"D08_validation_results.csv"),D09=file.path(dv_stage_dir("D09_missingness_detection_peptides"),"D09_unique_peptide_support.csv"))
missing<-files[!file.exists(files)];if(length(missing))dv_stop("D10 gate: missing finalized evidence table(s): ",paste(names(missing),collapse=", "))
base<-dv_read_csv(files["D03"],"PG.ProteinGroups");dv_assert_keys(base,"PG.ProteinGroups","D03 lock")
select_unique<-function(path,cols){x<-dv_read_csv(path,"PG.ProteinGroups");x<-x[!duplicated(x$PG.ProteinGroups),intersect(c("PG.ProteinGroups",cols),names(x)),drop=FALSE];x}
master<-base;master<-merge(master,select_unique(files["D04"],"Trajectory"),by="PG.ProteinGroups",all.x=TRUE,suffixes=c("","_D04"));master<-merge(master,select_unique(files["D08"],c("log2FC","Candidate_family_BH_FDR","Direction_concordant","Nominal_replication","FDR_supported_replication","Effect_difference_signed","Effect_difference_absolute")),by="PG.ProteinGroups",all.x=TRUE,suffixes=c("_Discovery","_Validation"));master<-merge(master,select_unique(files["D09"],c("Unique_peptide_count","Single_unique_peptide","Peptide_support_status")),by="PG.ProteinGroups",all.x=TRUE)
if(nrow(master)!=nrow(base)||!setequal(master$PG.ProteinGroups,base$PG.ProteinGroups))dv_stop("D10 unauthorized candidate expansion/loss")
# Pathway membership must be investigator-supplied before execution; no online enrichment or hidden universe.
pathmap<-file.path(DV_BASE,"D10_pathway_mapping.csv");if(file.exists(pathmap)){pm<-dv_read_csv(pathmap,c("PG.ProteinGroups","Pathway"));pathway<-merge(base["PG.ProteinGroups"],pm,by="PG.ProteinGroups",all.x=TRUE);inputs<-c(files,pathmap)}else{pathway<-data.frame(PG.ProteinGroups=base$PG.ProteinGroups,Pathway=NA_character_,Status="NOT_RUN_NO_APPROVED_MAPPING");inputs<-files}
paths<-file.path(outdir,c("D10_integrated_candidate_evidence.csv","D10_pathway_membership.csv","D10_manifest.csv"));dv_no_overwrite(paths);dv_write(master,paths[1]);dv_write(pathway,paths[2]);dv_write(dv_manifest(stage,inputs,paths[1:2],list(candidate_hash=hash,interpretation="supportive; no candidate redefinition",pathway_gate="approved mapping/universe required")),paths[3])
