#!/usr/bin/env Rscript
# R-only, result-table-only manuscript figures. No model fitting, FDR calculation,
# candidate selection, threshold tuning, or biological-data access is permitted here.
suppressPackageStartupMessages({library(ggplot2); library(patchwork)})
args <- commandArgs(trailingOnly=TRUE); if(length(args)!=2L)stop("Usage: Rscript figures_prospective.R FIGURE_ID OUTPUT_STEM")
root<-normalizePath(file.path(dirname(normalizePath(sub("^--file=", "", commandArgs(FALSE)[grep("^--file=",commandArgs(FALSE))]))),"..","..",".."),winslash="/",mustWork=FALSE);base<-file.path(root,"descriptive","discovery_validation")
read_result<-function(stage,file,cols){p<-file.path(base,stage,file);if(!file.exists(p))return(NULL);x<-read.csv(p,check.names=FALSE);m<-setdiff(cols,names(x));if(length(m))stop("Figure source contract missing: ",paste(m,collapse=", "));x}
theme_set(theme_classic(base_size=6.5,base_family="Arial")+theme(axis.line=element_line(linewidth=.35),axis.ticks=element_line(linewidth=.35),legend.text=element_text(size=5.8),strip.text=element_text(size=6.2,face="bold"),plot.title=element_text(size=7,face="bold")))
pal<-c(Control="#777777",Short="#3B82A0",Long="#C45A3D","Humid-hot"="#B24C63","High-pressure/high-altitude"="#3274A1")
nonempty<-function(x,msg)if(is.null(x)||!nrow(x))stop("NON_ESTIMABLE / missing finalized source: ",msg)else x
fig2<-function(){x<-nonempty(read_result("D02_discovery_primary","D02_Long_vs_Short_all_tested.csv",c("log2FC","BH_FDR")),"D02");x$plot_FDR<-pmax(x$BH_FDR,.Machine$double.xmin);ggplot(x,aes(log2FC,-log10(plot_FDR)))+geom_point(size=.7,alpha=.55,color="#777777")+geom_vline(xintercept=0,linetype=2)+labs(x="Discovery Long vs Short log2 fold change",y="−log10 BH FDR")}
fig3<-function(){x<-nonempty(read_result("D04_dose_trajectory","D04_modeled_abundance_by_dose.csv",c("PG.ProteinGroups","Dose","Modeled_mean","N_observed")),"D04");x$Dose<-factor(x$Dose,c("control","low","high"),c("Control","Short","Long"));ggplot(x,aes(Dose,Modeled_mean,group=PG.ProteinGroups))+geom_line(alpha=.2,color="#777777")+stat_summary(aes(group=1),fun=median,geom="line",linewidth=.9,color="#B24C63")+labs(x=NULL,y="Modeled log2 abundance",caption="Per-protein observed n retained in source data")}
fig4<-function(){x<-nonempty(read_result("D05_environment_specific","D05_candidate_environment_results.csv",c("Environment","Contrast","log2FC","CI_low","CI_high")),"D05");x<-x[x$Contrast=="Long_vs_Short"&is.finite(x$log2FC),];if(!nrow(x))stop("NON_ESTIMABLE");ggplot(x,aes(log2FC,reorder(PG.ProteinGroups,log2FC),color=Environment))+geom_vline(xintercept=0,linetype=2)+geom_errorbarh(aes(xmin=CI_low,xmax=CI_high),height=0)+geom_point(size=1)+scale_color_manual(values=pal)+labs(x="Long vs Short log2 fold change (95% CI)",y=NULL)}
fig5<-function(){x<-nonempty(read_result("D08_validation","D08_validation_results.csv",c("Discovery_log2FC","log2FC","CI_low","CI_high","Direction_concordant")),"D08");ggplot(x,aes(Discovery_log2FC,log2FC,color=Direction_concordant))+geom_abline(slope=1,intercept=0,linetype=2)+geom_hline(yintercept=0,color="#BBBBBB")+geom_vline(xintercept=0,color="#BBBBBB")+geom_point(size=1.2)+coord_equal()+scale_color_manual(values=c(`TRUE`="#2E7D65",`FALSE`="#B24C63"),na.value="#999999")+labs(x="Discovery log2 fold change",y="Validation log2 fold change",color="Direction concordant")}
fig6<-function(){x<-nonempty(read_result("D10_integrated_biology","D10_integrated_candidate_evidence.csv",c("PG.ProteinGroups","Direction_concordant","Peptide_support_status")),"D10");ggplot(x,aes(Peptide_support_status,fill=Direction_concordant))+geom_bar(position="fill")+coord_flip()+scale_fill_manual(values=c(`TRUE`="#2E7D65",`FALSE`="#B24C63"),na.value="#999999")+labs(x=NULL,y="Candidate proportion",fill="Validation direction concordant")}
fun<-switch(toupper(args[1]),FIG2=fig2,FIG3=fig3,FIG4=fig4,FIG5=fig5,FIG6=fig6,stop("Unknown figure ID"));p<-fun();stem<-args[2];dir.create(dirname(stem),recursive=TRUE,showWarnings=FALSE)
width_mm<-183;height_mm<-120;width_in<-width_mm/25.4;height_in<-height_mm/25.4
svglite::svglite(paste0(stem,".svg"),width=width_in,height=height_in);print(p);dev.off()
grDevices::cairo_pdf(paste0(stem,".pdf"),width=width_in,height=height_in,family="Arial");print(p);dev.off()
ragg::agg_tiff(paste0(stem,".tiff"),width=width_in,height=height_in,units="in",res=600,compression="lzw");print(p);dev.off()
